export const MENU_HELP_MODAL_VISIBLE = 'MENU_HELP_MODAL_VISIBLE';
export const MENU_SETTINGS_MODAL_VISIBLE = 'MENU_SETTINGS_MODAL_VISIBLE'

export const TILE_MAP_STATS_CHANGE = 'MAP_STATS_CHANGE';

export const GAME_STARTED = 'GAME_STARTED';

export const NATURE_ENERGY_CHANGE = 'NATURE_ENERGY_CHANGE';
export const NATURE_SELECTION_CHANGE = 'NATURE_SELECTION_CHANGE';
export const NATURE_SELECTION_OPTION_CHANGE = 'NATURE_SELECTION_OPTION_CHANGE';

export const NATURE_NEW_UNIT_BUILDERS = 'NATURE_NEW_UNIT_BUILDERS';
export const NATURE_NEW_UNIT_WARRIORS = 'NATURE_NEW_UNIT_WARRIORS';

export const NATURE_REMOVE_UNIT_BUILDERS = 'NATURE_REMOVE_UNIT_BUILDERS';
export const NATURE_REMOVE_UNIT_WARRIORS = 'NATURE_REMOVE_UNIT_WARRIORS';
