export const TILE_MAP_STATS_CHANGE = 'MAP_STATS_CHANGE';

export const NATURE_ENERGY_CHANGE = 'NATURE_ENERGY_CHANGE';
export const NATURE_SELECTION_CHANGE = 'NATURE_SELECTION_CHANGE';
export const NATURE_SELECTION_OPTION_CHANGE = 'NATURE_SELECTION_OPTION_CHANGE';