export const TILE_MAP_STATS_CHANGE = 'MAP_STATS_CHANGE';

export const NATURE_ENERGY_CHANGE = 'NATURE_ENERGY_CHANGE';
export const NATURE_SELECTION_CHANGE = 'NATURE_SELECTION_CHANGE';
export const NATURE_SELECTION_OPTION_CHANGE = 'NATURE_SELECTION_OPTION_CHANGE';

export const NATURE_NEW_UNIT_BUILDERS = 'NATURE_NEW_UNIT_BUILDERS';
export const NATURE_NEW_UNIT_WARRIORS = 'NATURE_NEW_UNIT_WARRIORS';

export const NATURE_REMOVE_UNIT_BUILDERS = 'NATURE_REMOVE_UNIT_BUILDERS';
export const NATURE_REMOVE_UNIT_WARRIORS = 'NATURE_REMOVE_UNIT_WARRIORS';
